### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by 1schlick** [Ivan-1F/Ivan-Carpet-Addition#14]
Title

**Comment by venaminecraft** [comment]
Hello, I would love to have the mod for 1.19.3 as well.

**Comment by Ivan-1F** [comment]
1.19.3 fabric-carpet made some very complex api change, it may take times to compat

**Comment by Ivan-1F** [comment]
[v2.2.1](https://github.com/Ivan-1F/Ivan-Carpet-Addition/releases/tag/v2.2.1) released

**Comment by venaminecraft** [comment]
Thanks again 🥳
