### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [Ivan-1F/Ivan-Carpet-Addition#19]

**Comment by GobezkidMC** [comment]
Yes my server members miss this mod as it allowed for some great builds

**Comment by venaminecraft** [comment]
I think it's for now from the table, Ivan is currently too busy 😪

**Comment by Ivan-1F** [comment]
You can use the build from https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/8485705662

**Comment by venaminecraft** [comment]
You are back!! ❤️
Thanks, I will test the new version the following days.

Could you update to 1.20.4 please as well?

**Comment by Ivan-1F** [comment]
I will add support for the remaining 1.20 versions soon

**Comment by venaminecraft** [comment]
Awesome!!

**Comment by venaminecraft** [comment]
Any update @Ivan-1F? 😄

**Comment by Ivan-1F** [comment]
1.20.1: https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/8485705662
1.20.2: https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/8893355379
1.20.3, 1.20.4: https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/8893356249
1.20.5 https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/8893357213

**Comment by venaminecraft** [comment]
Big thanks 🥳

1.20.6 came in time, but this can wait 😆

**Comment by Ivan-1F** [comment]
Released: https://github.com/Ivan-1F/Ivan-Carpet-Addition/releases/tag/v3.0.0

**Comment by venaminecraft** [comment]
Thanks!! 🥳
