### ISSUE TITLE
bannedMobs可以自定义生物吗，同时采用true/false方式

### ISSUE THREAD

**Issue by 991200448** [Ivan-1F/Ivan-Carpet-Addition#2]
由于玩空岛想禁用蝙蝠(满天飞)，希望bannedMobs能实现自定义生物同时可以开启/关闭，谢谢

**Comment by Ivan-1F** [comment]
设置为 `_` 即可禁用：`/carpet bannedMobs _`

禁用蝙蝠的话用 `/carpet bannedMobs bat` 就行

**Comment by 991200448** [comment]
又测试了一下 发现这个指令bannedMobs好像没效果,只禁了zombie，carpet.conf为bannedMobs zombie，但是zombie会生成

**Comment by Ivan-1F** [comment]
这个功能刚刚进行了重构，拆分为三个规则：

 - 生物生成限制模式 (mobSpawningRestrictionMode)
 - 生物黑名单 (mobBlackList)
 - 生物白名单 (mobWhiteList)

如果你想禁用某种生物的话，把 `mobSpawningRestrictionMode` 设置为 `blacklist`，并在 `mobBlackList` 中设置需要禁用的生物

你可以先从最新的 GitHub Actions 下载使用，我会在经过进一步的测试后发布

**Comment by Ivan-1F** [comment]
GitHub Actions 链接：

 - [1.15.2](https://github.com/Ivan-YFw/Ivan-Carpet-Addition/suites/2121582389/artifacts/43259477)
 - [1.16.4](https://github.com/Ivan-YFw/Ivan-Carpet-Addition/suites/2121744304/artifacts/43263473)
 - [21w08a](https://github.com/Ivan-YFw/Ivan-Carpet-Addition/suites/2121909346/artifacts/43268320)
 - [1.14.4](https://github.com/Ivan-YFw/Ivan-Carpet-Addition/suites/2122009266/artifacts/43271025)

**Comment by 991200448** [comment]
启动了指令，但是怪还是会生成，是不是限制刷怪的代码那出了点问题

**Comment by 991200448** [comment]
虽然我不是很懂java，但是我觉得应该是返回值都是false导致的

public class ServerWorldMixin {
    @Inject(method = "spawnEntity", at = @At("HEAD"), cancellable = true)
    private void spawnEntity(Entity entity, CallbackInfoReturnable<Boolean> cir) {
        if (IvanCarpetAdditionSettings.mobSpawningRestrictionMode.equals("blacklist")) {
            Set<String> blackList = Sets.newLinkedHashSet(Arrays.asList(IvanCarpetAdditionSettings.mobBlackList.split(",")));
            if (blackList.contains(entity.getName().getString().toLowerCase())) {
                cir.setReturnValue(false);
            }
        }
        if (IvanCarpetAdditionSettings.mobSpawningRestrictionMode.equals("whitelist")) {
            Set<String> whitelist = Sets.newLinkedHashSet(Arrays.asList(IvanCarpetAdditionSettings.mobWhiteList.split(",")));
            if (!whitelist.contains(entity.getName().getString().toLowerCase())) {
                cir.setReturnValue(false);
            }
        }
    }
}

**Comment by Ivan-1F** [comment]
返回值是false代表刷怪失败，设置返回值后就强行切断接下来的刷怪逻辑了

我这里 1.14.4~1.17 都测试过了没问题，如果不能正常工作的话请提供一下 MC 版本、carpet.conf 和加载的Mod列表

**Comment by 991200448** [comment]
版本1.16.5

carpet.conf:
mobBlackList bat
mobSpawningRestrictionMode blacklist

mod:就用了三个模组测试
ivan-carpet-addition-1.3.0+build.98.jar
[Fabric-API] fabric-api-0.30.3+1.16.jar
fabric-carpet-1.16.5-1.4.27+v210217.jar

**Comment by Ivan-1F** [comment]
是还会自然生成吗？开一个超平坦世界试试，看看有没有抑制效果

目前这个版本还有一个改动：在更改设置后不会清除已有的生物了，如果需要清除的话可以先用kill

**Comment by 991200448** [comment]
我就是开了超平坦测试的，没效果，往未加载的区块跑还是会生成怪，你可以加我qq我可以测试结果给你看，qq就是我名字
