### ISSUE TITLE
This is just a question.

### ISSUE THREAD

**Issue by QPCrummer** [Ivan-1F/Ivan-Carpet-Addition#4]
The description of IcasyncProtocal isn't very descriptive. What exactly does it do and does it benefit a server. Also, does it have any consequences for enabling it?

**Comment by Ivan-1F** [comment]
IcaSyncProtocol is still in development. Some client-side mods need entities and block entities data to work properly. However, client-side mods can't get these data by themselves. If you enable this rule, client-side mods can require data from the server and the server will send back a packet with the data. I also planned to add more features to it to give more permission to client-side mods, and I will open this protocol to developers in the future.
