### ISSUE TITLE
Deprecated registerExtension position in 1.19

### ISSUE THREAD

**Issue by ghost** [Ivan-1F/Ivan-Carpet-Addition#9]
Hello, I got this from my server log:

[main/WARN]: Extension 'IvanCarpetAdditionServer' is registering itself using a mixin into Carpet instead of a regular ModInitializer!
This is stupid and will crash the game in future versions!

**Comment by Ivan-1F** [comment]
This is a 1.19 compatibility issue with carpet

Fixed in https://github.com/Ivan-1F/Ivan-Carpet-Addition/commit/fcde0cc4c9c56c95340af785a25200fdbfff6db4

You can get the latest build here: https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/2503637430

This will be released soon

**Comment by ghost** [comment]
Thank you so much:)
